'use client';
import {useCallback,useEffect,useState} from 'react';
import {Eye,EyeOff,Save,Wifi,RefreshCw,KeyRound} from 'lucide-react';
const KEYS=[
 ['LEONARDO_API_KEY','Leonardo AI'],['HUGGINGFACE_API_KEY','Hugging Face'],
 ['PRINTFUL_API_KEY','Printful'],['PRINTIFY_API_KEY','Printify'],
 ['STRIPE_SECRET_KEY','Stripe Secret'],['STRIPE_PUBLISHABLE_KEY','Stripe Publishable'],
 ['TIKTOK_ACCESS_TOKEN','TikTok Access Token'],['INSTAGRAM_ACCESS_TOKEN','Instagram Access Token'],
 ['FACEBOOK_ACCESS_TOKEN','Facebook Access Token'],['PINTEREST_ACCESS_TOKEN','Pinterest Access Token']
];
export default function ApiKeySettings(){
 const [status,setStatus]=useState({}),[values,setValues]=useState({}),[visible,setVisible]=useState({}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/settings',{credentials:'include',cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'تعذر تحميل حالات المفاتيح');setStatus(Object.fromEntries((d.settings||[]).map(x=>[x.key,x])))}catch(e){setError(e.message)}},[]);
 useEffect(()=>{load()},[load]);
 async function save(key){setBusy(key);setError('');setNotice('');try{const value=values[key]||'';if(value.length<4)throw Error('أدخل المفتاح أولاً');const r=await fetch('/api/settings',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({key,value})}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الحفظ');setValues(v=>({...v,[key]:''}));setNotice('تم حفظ '+key+' مشفرًا في قاعدة البيانات.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
 async function test(key){setBusy(key);setError('');setNotice('');try{const r=await fetch('/api/settings/test',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الاختبار');setNotice(d.message||'نجح الاختبار.')}catch(e){setError(e.message)}finally{setBusy('')}}
 return <section className="mt-6 border-t border-out-gold/25 pt-5"><h3 className="mb-1 flex items-center gap-2 text-lg font-black text-white"><KeyRound className="h-5 w-5 text-out-gold"/>مفاتيح API</h3><p className="mb-4 text-xs text-out-silver">تُحفظ القيم مشفرة AES-256-GCM في قاعدة البيانات. لا تُعرض المفاتيح المحفوظة؛ أدخل قيمة جديدة لاستبدالها.</p>
 <div className="space-y-3">{KEYS.map(([key,label])=><div key={key} className="rounded-xl border border-out-border bg-out-card p-3"><div className="mb-2 flex items-center justify-between gap-2"><label htmlFor={'api-'+key} className="text-sm font-bold text-white">{label}</label><span className={'text-xs '+(status[key]?.configured?'text-green-400':'text-out-silver')}>{status[key]?.configured?'مُعد':'غير مُعد'}</span></div><div className="flex gap-2"><input id={'api-'+key} type={visible[key]?'text':'password'} autoComplete="new-password" value={values[key]||''} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))} placeholder={status[key]?.configured?'محفوظ — أدخل قيمة جديدة للتغيير':'أدخل المفتاح'} className="min-w-0 flex-1 rounded-lg border border-out-border bg-black/30 p-2 text-sm text-white"/><button type="button" onClick={()=>setVisible(v=>({...v,[key]:!v[key]}))} aria-label={visible[key]?'إخفاء المفتاح':'إظهار المفتاح'} className="rounded-lg border border-out-border px-3 text-out-silver">{visible[key]?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div><div className="mt-2 flex gap-2"><button type="button" onClick={()=>save(key)} disabled={busy===key||!(values[key]||'').trim()} className="flex items-center gap-1 rounded-lg bg-out-gold px-3 py-2 text-xs font-bold text-black disabled:opacity-50"><Save className="h-3 w-3"/>حفظ</button>{['LEONARDO_API_KEY','HUGGINGFACE_API_KEY','PRINTFUL_API_KEY','PRINTIFY_API_KEY','STRIPE_SECRET_KEY'].includes(key)&&status[key]?.configured&&<button type="button" onClick={()=>test(key)} disabled={busy===key} className="flex items-center gap-1 rounded-lg border border-out-border px-3 py-2 text-xs text-sky-300"><Wifi className="h-3 w-3"/>اختبار</button>}</div></div>)}</div>
 {error&&<p role="alert" className="mt-3 text-sm text-red-400">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-green-300">{notice}</p>}<button type="button" onClick={load} className="mt-3 flex items-center gap-2 text-xs text-out-silver"><RefreshCw className="h-3 w-3"/>تحديث الحالات</button></section>
}
