'use client';
import { useEffect,useState } from 'react';
import { motion,AnimatePresence } from 'framer-motion';
import { X,Trash2,ShoppingBag,Plus,Minus } from 'lucide-react';
import { formatPrice } from '@/lib/safe-format';
const STORAGE_KEY='out_cart_v1';
function readCart(){try{const parsed=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(parsed)?parsed:[]}catch{return[]}}
export default function CartDrawer({isOpen,onClose,onCheckout}){
 const[items,setItems]=useState([]);
 useEffect(()=>{setItems(readCart());function handleAdd(event){const product=event.detail;if(!product?.id)return;setItems(prev=>{const found=prev.find(item=>item.productId===product.id);if(found)return prev.map(item=>item.productId===product.id?{...item,quantity:item.quantity+1}:item);return[...prev,{productId:product.id,name:product.name_ar||product.name_en||'OUT Product',price_cents:Number(product.price_cents||0),image:product.designs?.thumbnail_url||product.designs?.image_url||'/placeholder.svg',quantity:1}]})}function handleStorage(){setItems(readCart())}window.addEventListener('out:add-to-cart',handleAdd);window.addEventListener('storage',handleStorage);return()=>{window.removeEventListener('out:add-to-cart',handleAdd);window.removeEventListener('storage',handleStorage)}},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(items));window.dispatchEvent(new CustomEvent('out:cart-updated',{detail:{items}}))}catch{}},[items]);
 const subtotal=items.reduce((s,i)=>s+Number(i.price_cents||0)*i.quantity,0),shipping=subtotal>5000?0:subtotal>0?800:0,total=subtotal+shipping;
 const updateQty=(id,delta)=>setItems(prev=>prev.map(i=>i.productId===id?{...i,quantity:Math.max(0,i.quantity+delta)}:i).filter(i=>i.quantity>0));
 return <AnimatePresence>{isOpen&&<><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose} className="fixed inset-0 bg-black/70 backdrop-blur-sm z-40"/><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{type:'spring',damping:25}} className="fixed top-0 right-0 h-full w-full sm:w-96 bg-out-dark border-l border-out-gold/30 z-50 flex flex-col" dir="rtl"><div className="flex items-center justify-between p-5 border-b border-out-border"><div className="flex items-center gap-2"><ShoppingBag className="w-5 h-5 text-out-gold"/><h2 className="text-lg font-bold text-white">السلة ({items.reduce((n,i)=>n+i.quantity,0)})</h2></div><button type="button" onClick={onClose} aria-label="إغلاق"><X className="w-5 h-5"/></button></div><div className="flex-1 overflow-y-auto p-5 space-y-3">{!items.length?<div className="text-center py-12 text-out-silver/60"><ShoppingBag className="w-12 h-12 mx-auto mb-3 opacity-30"/><p>السلة فارغة</p></div>:items.map(item=><div key={item.productId} className="flex gap-3 bg-out-card border border-out-border rounded-xl p-3"><img src={item.image||'/placeholder.svg'} alt={item.name} className="w-16 h-16 rounded-lg object-cover flex-shrink-0"/><div className="flex-1 min-w-0"><h3 className="text-white text-sm font-bold truncate mb-1">{item.name}</h3><p className="text-out-gold text-sm font-bold mb-2">${formatPrice(item.price_cents)}</p><div className="flex items-center justify-between"><div className="flex items-center gap-1 bg-out-dark rounded-lg border border-out-border"><button type="button" onClick={()=>updateQty(item.productId,-1)} aria-label="إنقاص"><Minus className="w-3 h-3"/></button><span className="w-6 text-center text-white text-sm">{item.quantity}</span><button type="button" onClick={()=>updateQty(item.productId,1)} aria-label="زيادة"><Plus className="w-3 h-3"/></button></div><button type="button" onClick={()=>setItems(prev=>prev.filter(i=>i.productId!==item.productId))} className="text-red-400" aria-label="حذف"><Trash2 className="w-4 h-4"/></button></div></div></div>)}</div>{items.length>0&&<div className="border-t border-out-border p-5 space-y-3"><div className="flex justify-between text-sm text-out-silver"><span>المجموع الفرعي</span><span>${formatPrice(subtotal)}</span></div><div className="flex justify-between text-sm text-out-silver"><span>الشحن</span><span>{shipping===0?'مجاني':formatPrice(shipping)}</span></div><div className="flex justify-between text-lg font-bold text-white pt-3 border-t border-out-border"><span>الإجمالي</span><span className="text-out-gold">${formatPrice(total)}</span></div><button type="button" onClick={()=>onCheckout?.(items,total)} className="w-full bg-gradient-to-r from-out-gold to-out-gold-light text-out-black font-bold py-3 rounded-xl">إتمام الشراء</button><button type="button" onClick={()=>setItems([])} className="w-full text-out-silver text-sm">إفراغ السلة</button></div>}</motion.aside></>}</AnimatePresence>
}
export function addToCart(product){if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('out:add-to-cart',{detail:product}))}
