'use client';
import {useCallback,useEffect,useState} from 'react';
import {Plus,Save,RefreshCw,Trash2,Wifi} from 'lucide-react';
const empty={platform_name:'',api_type:'api',api_key:''};
export default function PodConfigManager(){const [items,setItems]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[showForm,setShowForm]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
const load=useCallback(async()=>{try{const r=await fetch('/api/pod-config',{credentials:'include',cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل تحميل المواقع');setItems(d.platforms||[])}catch(e){setError(e.message)}},[]);useEffect(()=>{load()},[load]);
async function save(e){e.preventDefault();setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/pod-config',{method:editing?'PUT':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(editing?{id:editing,...form}:{...form})}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الحفظ');setShowForm(false);setEditing(null);setForm(empty);setNotice('حُفظ الإعداد. المفتاح مخزن مشفرًا.');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
async function test(id){setError('');setNotice('');try{const r=await fetch('/api/pod-config',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test',id})}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الاختبار');setNotice(d.message);await load()}catch(e){setError(e.message)}}
async function remove(id){if(!confirm('حذف موقع POD؟'))return;const r=await fetch('/api/pod-config',{method:'DELETE',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})}),d=await r.json();if(!r.ok){setError(d.error||'فشل الحذف');return}await load()}
return <div className="space-y-3"><button onClick={()=>{setEditing(null);setForm(empty);setShowForm(true)}} className="flex items-center gap-2 rounded-lg border border-dashed border-out-gold/50 px-3 py-2 text-out-gold"><Plus className="h-4 w-4"/>+ إضافة موقع POD جديد</button>
{showForm&&<form onSubmit={save} className="space-y-3 rounded-xl border border-out-border bg-out-card p-4"><label className="block text-sm text-out-silver">اسم الموقع<input required maxLength={100} disabled={Boolean(editing)} value={form.platform_name} onChange={e=>setForm({...form,platform_name:e.target.value})} placeholder="اسم موقع POD" className="mt-1 w-full rounded-lg border border-out-border bg-black/30 p-2 text-white"/></label><label className="block text-sm text-out-silver">نوع API<select value={form.api_type} onChange={e=>setForm({...form,api_type:e.target.value})} className="mt-1 w-full rounded-lg border border-out-border bg-out-black p-2 text-white"><option value="api">API</option><option value="rpa">RPA</option></select></label><label className="block text-sm text-out-silver">مفتاح API<input type="password" autoComplete="new-password" required={!editing} value={form.api_key} onChange={e=>setForm({...form,api_key:e.target.value})} placeholder={editing?'اتركه فارغًا للإبقاء على المفتاح الحالي':'أدخل مفتاح API'} className="mt-1 w-full rounded-lg border border-out-border bg-black/30 p-2 text-white"/></label><div className="flex gap-2"><button disabled={busy} className="flex items-center gap-2 rounded-lg bg-out-gold px-4 py-2 font-bold text-black"><Save className="h-4 w-4"/>حفظ</button><button type="button" onClick={()=>setShowForm(false)} className="rounded-lg border border-out-border px-4 py-2 text-white">إلغاء</button></div></form>}
{items.map(x=><div key={x.id} className="rounded-xl border border-out-border bg-out-card p-3"><div className="flex items-start justify-between gap-2"><div><b className="text-white">{x.platform_name}</b><p className="text-xs text-out-silver">{x.api_type.toUpperCase()} · {x.has_api_key?'مفتاح محفوظ مشفر':'غير مهيأ'}</p><p className={'mt-1 text-xs '+(x.is_active?'text-green-400':'text-amber-300')}>{x.is_active?'مربوط ✅':'غير مهيأ'}</p>{x.test_status==='manual_check_required'&&<p className="mt-1 text-xs text-amber-200">وجود المفتاح فقط مؤكد؛ صلاحيته لم تُتحقق من المزود.</p>}</div><div className="flex flex-wrap gap-2"><button onClick={()=>{setEditing(x.id);setForm({platform_name:x.platform_name,api_type:x.api_type,api_key:''});setShowForm(true)}} className="text-xs text-out-gold">تعديل</button><button onClick={()=>test(x.id)} className="flex items-center gap-1 text-xs text-sky-300"><Wifi className="h-3 w-3"/>اختبار الاتصال</button><button onClick={()=>remove(x.id)} aria-label="حذف" className="text-red-300"><Trash2 className="h-4 w-4"/></button></div></div></div>)}
{error&&<p role="alert" className="text-sm text-red-400">{error}</p>}{notice&&<p role="status" className="text-sm text-green-300">{notice}</p>}<button onClick={load} className="flex items-center gap-2 text-xs text-out-silver"><RefreshCw className="h-3 w-3"/>تحديث القائمة</button></div>}
