'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ShoppingCart, Heart, Star } from 'lucide-react';
import { formatPrice } from '@/lib/safe-format';

export default function ProductGrid({ category = null, search = '', onAddToCart }) {
  const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();async function load(){setLoading(true);setError('');try{const params=new URLSearchParams();if(category&&category!=='all')params.set('category',category);if(search.trim())params.set('search',search.trim());params.set('limit','24');const res=await fetch(`/api/products?${params.toString()}`,{signal:controller.signal,credentials:'include',cache:'no-store'});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'فشل تحميل المنتجات');setProducts(Array.isArray(data.products)?data.products:[]);}catch(e){if(e.name!=='AbortError')setError(e.message||'فشل تحميل المنتجات')}finally{if(!controller.signal.aborted)setLoading(false)}}const timer=setTimeout(load,300);return()=>{clearTimeout(timer);controller.abort()};},[category,search]);
  if(loading)return <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">{Array.from({length:8}).map((_,i)=><div key={i} className="bg-out-card border border-out-border rounded-2xl overflow-hidden animate-pulse"><div className="aspect-[4/5] bg-out-border/40"/><div className="p-4 space-y-2"><div className="h-4 bg-out-border/40 rounded w-3/4"/><div className="h-3 bg-out-border/40 rounded w-1/2"/><div className="h-6 bg-out-border/40 rounded w-1/3 mt-3"/></div></div>)}</div>;
  if(error)return <div className="text-center py-12 text-red-400">⚠️ {error}</div>;
  if(!products.length)return <div className="text-center py-12 text-out-silver/60"><p className="text-lg">لا توجد منتجات مطابقة</p></div>;
  return <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">{products.map((product,i)=>{const image=product.designs?.thumbnail_url||product.designs?.image_url||'/placeholder.svg';const rating=Number(product.rating??5);return <motion.article key={product.id} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:Math.min(i*0.03,0.4)}} className="group bg-out-card border border-out-border rounded-2xl overflow-hidden hover:border-out-gold hover:shadow-gold transition"><div className="relative aspect-[4/5] overflow-hidden bg-out-dark"><Image src={image} alt={product.name_ar||product.name_en||'OUT product'} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw" className="object-cover group-hover:scale-105 transition duration-500" loading="lazy"/><button type="button" onClick={e=>e.stopPropagation()} className="absolute top-3 right-3 w-9 h-9 rounded-full bg-black/50 backdrop-blur flex items-center justify-center text-white hover:text-red-400" aria-label="أضف للمفضلة"><Heart className="w-4 h-4"/></button></div><div className="p-4"><h3 className="text-white font-bold text-sm mb-1 truncate">{product.name_ar||product.name_en}</h3><div className="flex items-center gap-2 text-out-silver text-xs mb-3"><span className="flex items-center gap-1"><Star className="w-3 h-3 fill-out-gold text-out-gold"/>{Number.isFinite(rating)?rating.toFixed(1):'5.0'}</span><span>•</span><span>{product.sales_count||0} مبيع</span></div><div className="flex items-center justify-between gap-2"><span className="text-out-gold font-bold text-lg">${formatPrice(product.price_cents)}</span><button type="button" onClick={()=>onAddToCart?.(product)} className="w-9 h-9 rounded-lg bg-gradient-to-r from-out-gold to-out-gold-light text-out-black flex items-center justify-center hover:shadow-gold" aria-label="أضف للسلة"><ShoppingCart className="w-4 h-4"/></button></div></div></motion.article>})}</div>;
}
