'use client';
import {useCallback,useEffect,useState} from 'react';
import {Save,Wifi,RefreshCw} from 'lucide-react';
const names=['TikTok','Instagram','Facebook','Pinterest'];
export default function SocialConfigManager(){const [items,setItems]=useState([]),[forms,setForms]=useState({}),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState('');
const load=useCallback(async()=>{try{const r=await fetch('/api/social-config',{credentials:'include',cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل تحميل المنصات');setItems(d.platforms||[])}catch(e){setError(e.message)}},[]);useEffect(()=>{load()},[load]);
function change(p,k,v){setForms(old=>({...old,[p]:{...(old[p]||{}),[k]:v}}))}
async function save(p){setBusy(p);setError('');setNotice('');try{const row=items.find(x=>x.platform_name===p),f=forms[p]||{},payload=row?{id:row.id,account_name:f.account_name??row.account_name,access_token:f.access_token||''}:{platform_name:p,account_name:f.account_name||'',access_token:f.access_token||''};const r=await fetch('/api/social-config',{method:row?'PUT':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الحفظ');setForms(old=>({...old,[p]:{account_name:d.platform.account_name,access_token:''}}));setNotice('تم حفظ الإعدادات والرمز مشفرًا.');await load()}catch(e){setError(e.message)}finally{setBusy('')}}
async function test(row){setError('');setNotice('');try{const r=await fetch('/api/social-config',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'test',id:row.id})}),d=await r.json();if(!r.ok)throw Error(d.error||'فشل الفحص');setNotice(d.message)}catch(e){setError(e.message)}}
return <div className="space-y-4">{names.map(p=>{const row=items.find(x=>x.platform_name===p),f=forms[p]||{};return <section key={p} className="space-y-3 rounded-xl border border-out-border bg-out-card p-4"><div className="flex items-center justify-between"><h4 className="font-bold text-white">{p}</h4><span className={'text-xs '+(row?.is_active?'text-green-400':'text-out-silver')}>{row?.is_active?'مربوط ✅':'غير مربوط'}</span></div><label className="block text-xs text-out-silver">اسم الحساب/الصفحة<input maxLength={150} value={f.account_name??row?.account_name??''} onChange={e=>change(p,'account_name',e.target.value)} placeholder="اسم الحساب أو الصفحة" className="mt-1 w-full rounded-lg border border-out-border bg-out-black p-2 text-white"/></label><label className="block text-xs text-out-silver">مفتاح API / Access Token<input type="password" autoComplete="new-password" value={f.access_token||''} onChange={e=>change(p,'access_token',e.target.value)} placeholder={row?.has_access_token?'محفوظ؛ أدخل رمزًا جديدًا للتغيير':'أدخل Access Token'} className="mt-1 w-full rounded-lg border border-out-border bg-out-black p-2 text-white"/></label><div className="flex gap-3"><button onClick={()=>save(p)} disabled={busy===p} className="flex items-center gap-2 rounded-lg bg-out-gold px-3 py-2 text-sm font-bold text-black"><Save className="h-4 w-4"/>حفظ</button>{row&&<button onClick={()=>test(row)} className="flex items-center gap-2 rounded-lg border border-out-border px-3 py-2 text-sm text-sky-300"><Wifi className="h-4 w-4"/>اختبار الاتصال</button>}</div></section>})}
{error&&<p role="alert" className="text-sm text-red-400">{error}</p>}{notice&&<p role="status" className="text-sm text-green-300">{notice}</p>}<button onClick={load} className="flex items-center gap-2 text-xs text-out-silver"><RefreshCw className="h-3 w-3"/>تحديث</button><p className="text-xs text-amber-200">حفظ الرمز لا يعني أن الحساب مرتبط؛ يلزم تكامل API رسمي للتحقق من صلاحية الرمز وتفعيل الربط.</p></div>}
