import {NextResponse} from 'next/server';
import {getSupabaseAdmin} from '@/lib/supabase';
import {requireAdmin} from '@/lib/admin-api-auth';
import {encryptSecret} from '@/lib/secret-crypto';
export const runtime='nodejs';
const out=(b,s=200)=>NextResponse.json(b,{status:s,headers:{'Cache-Control':'no-store'}});
const safe=r=>({id:r.id,platform_name:r.platform_name,has_access_token:Boolean(r.access_token),account_name:r.account_name||'',is_active:Boolean(r.is_active),last_post:r.last_post,created_at:r.created_at});
const allowed=['TikTok','Instagram','Facebook','Pinterest'];
export async function GET(req){const a=await requireAdmin(req,['marketing']);if(a.error)return a.error;try{const {data,error}=await getSupabaseAdmin().from('social_platforms_config').select('*').order('created_at',{ascending:true});if(error)throw error;return out({platforms:(data||[]).map(safe)})}catch(e){console.error('[social-config GET]',e.message);return out({error:'تعذر قراءة إعدادات التواصل؛ تحقق من migrations.'},500)}}
export async function POST(req){const a=await requireAdmin(req,['marketing']);if(a.error)return a.error;try{const b=await req.json(),db=getSupabaseAdmin();if(b.action==='test'){const {data,error}=await db.from('social_platforms_config').select('id,access_token').eq('id',b.id).single();if(error)throw error;if(!data.access_token)return out({error:'أضف Access Token أولاً'},400);return out({success:true,test_status:'manual_check_required',message:'تم التأكد من وجود الرمز فقط؛ يلزم اختبار رسمي عبر API الخاص بالمنصة لتأكيد الصلاحية.'})}
if(!allowed.includes(b.platform_name)||typeof b.account_name!=='string'||b.account_name.length>150||typeof b.access_token!=='string'||!b.access_token.trim())return out({error:'المنصة واسم الحساب والرمز مطلوبة'},400);const {data,error}=await db.from('social_platforms_config').insert({platform_name:b.platform_name,account_name:b.account_name.trim(),access_token:encryptSecret(b.access_token.trim()),is_active:false}).select('*').single();if(error){if(error.code==='23505')return out({error:'المنصة موجودة مسبقًا؛ استخدم تعديل'},409);throw error}return out({success:true,platform:safe(data)},201)}catch(e){console.error('[social-config POST]',e.message);return out({error:e.message.includes('APP_ENCRYPTION_KEY')?'يجب ضبط APP_ENCRYPTION_KEY في بيئة الخادم':'تعذر حفظ إعداد المنصة'},500)}}
export async function PUT(req){const a=await requireAdmin(req,['marketing']);if(a.error)return a.error;try{const b=await req.json();if(!b.id)return out({error:'معرّف المنصة مطلوب'},400);const p={is_active:false};if(typeof b.account_name==='string')p.account_name=b.account_name.trim().slice(0,150);if(typeof b.access_token==='string'&&b.access_token.trim())p.access_token=encryptSecret(b.access_token.trim());const {data,error}=await getSupabaseAdmin().from('social_platforms_config').update(p).eq('id',b.id).select('*').single();if(error)throw error;return out({success:true,platform:safe(data)})}catch(e){console.error('[social-config PUT]',e.message);return out({error:e.message.includes('APP_ENCRYPTION_KEY')?'يجب ضبط APP_ENCRYPTION_KEY في بيئة الخادم':'تعذر تعديل إعداد المنصة'},500)}}
export async function DELETE(req){const a=await requireAdmin(req,['marketing']);if(a.error)return a.error;try{const b=await req.json();if(!b.id)return out({error:'معرّف المنصة مطلوب'},400);const {error}=await getSupabaseAdmin().from('social_platforms_config').delete().eq('id',b.id);if(error)throw error;return out({success:true})}catch(e){console.error('[social-config DELETE]',e.message);return out({error:'تعذر حذف إعداد المنصة'},500)}}
