import {NextResponse} from 'next/server';
import {getSupabaseAdmin} from '@/lib/supabase';
import {requireAdmin} from '@/lib/admin-api-auth';
import {encryptSecret} from '@/lib/secret-crypto';
export const runtime='nodejs';
const out=(b,s=200)=>NextResponse.json(b,{status:s,headers:{'Cache-Control':'no-store'}});
const safe=r=>({id:r.id,platform_name:r.platform_name,api_type:r.api_type,has_api_key:Boolean(r.api_key),is_active:Boolean(r.is_active),last_tested:r.last_tested,test_status:r.test_status,created_at:r.created_at});
export async function GET(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const {data,error}=await getSupabaseAdmin().from('pod_platforms_config').select('*').order('created_at',{ascending:false});if(error)throw error;return out({platforms:(data||[]).map(safe)})}catch(e){console.error('[pod-config GET]',e.message);return out({error:'تعذر قراءة إعدادات POD؛ تحقق من migrations.'},500)}}
export async function POST(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const b=await req.json(),db=getSupabaseAdmin();if(b.action==='test'){const {data,error}=await db.from('pod_platforms_config').select('id,api_key').eq('id',b.id).single();if(error)throw error;if(!data.api_key)return out({error:'أضف مفتاح API أولاً'},400);const {error:ue}=await db.from('pod_platforms_config').update({last_tested:new Date().toISOString(),test_status:'manual_check_required',is_active:false}).eq('id',b.id);if(ue)throw ue;return out({success:true,test_status:'manual_check_required',message:'تم التأكد من وجود المفتاح فقط؛ لا يمكن تأكيد صلاحيته دون اختبار رسمي خاص بالمزود.'})}
if(typeof b.platform_name!=='string'||!b.platform_name.trim()||b.platform_name.length>100||!['api','rpa'].includes(b.api_type))return out({error:'اسم الموقع ونوع API مطلوبان'},400);const {data,error}=await db.from('pod_platforms_config').insert({platform_name:b.platform_name.trim(),api_type:b.api_type,api_key:encryptSecret(String(b.api_key||'')),is_active:false,test_status:'not_tested'}).select('*').single();if(error){if(error.code==='23505')return out({error:'الموقع موجود مسبقًا'},409);throw error}return out({success:true,platform:safe(data)},201)}catch(e){console.error('[pod-config POST]',e.message);return out({error:e.message.includes('APP_ENCRYPTION_KEY')?'يجب ضبط APP_ENCRYPTION_KEY في بيئة الخادم':'تعذر حفظ إعداد POD'},500)}}
export async function PUT(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const b=await req.json();if(!b.id)return out({error:'معرّف الموقع مطلوب'},400);const p={is_active:false,test_status:'not_tested'};if(typeof b.platform_name==='string')p.platform_name=b.platform_name.trim().slice(0,100);if(['api','rpa'].includes(b.api_type))p.api_type=b.api_type;if(typeof b.api_key==='string'&&b.api_key.trim())p.api_key=encryptSecret(b.api_key.trim());const {data,error}=await getSupabaseAdmin().from('pod_platforms_config').update(p).eq('id',b.id).select('*').single();if(error)throw error;return out({success:true,platform:safe(data)})}catch(e){console.error('[pod-config PUT]',e.message);return out({error:e.message.includes('APP_ENCRYPTION_KEY')?'يجب ضبط APP_ENCRYPTION_KEY في بيئة الخادم':'تعذر تعديل إعداد POD'},500)}}
export async function DELETE(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const b=await req.json();if(!b.id)return out({error:'معرّف الموقع مطلوب'},400);const {error}=await getSupabaseAdmin().from('pod_platforms_config').delete().eq('id',b.id);if(error)throw error;return out({success:true})}catch(e){console.error('[pod-config DELETE]',e.message);return out({error:'تعذر حذف الموقع'},500)}}
