import {NextResponse} from 'next/server';
import {getSupabaseAdmin} from '@/lib/supabase';
import {requireAdmin} from '@/lib/admin-api-auth';
export const runtime='nodejs';
const out=(body,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const {data,error}=await getSupabaseAdmin().from('brand_settings').select('brand_logo_url,brand_title,contact_email').eq('id',1).maybeSingle();if(error)throw error;return out({settings:{brandLogo:data?.brand_logo_url||'',brandTitle:data?.brand_title||'',email:data?.contact_email||''}})}catch(e){console.error('[brand-settings GET]',e.message);return out({error:'تعذر قراءة الإعدادات؛ تحقق من migrations.'},500)}}
export async function PUT(req){const a=await requireAdmin(req,['production']);if(a.error)return a.error;try{const b=await req.json(),db=getSupabaseAdmin();let logoUrl;
if(Object.hasOwn(b,'logoDataUrl')){const m=typeof b.logoDataUrl==='string'&&b.logoDataUrl.match(/^data:(image\/(?:png|jpeg|webp|svg\+xml));base64,([A-Za-z0-9+/=]+)$/);if(!m)return out({error:'صيغة الصورة غير مقبولة'},400);const bytes=Buffer.from(m[2],'base64');if(!bytes.length||bytes.length>2*1024*1024)return out({error:'الحد الأقصى للصورة 2 ميغابايت'},413);const ext={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/svg+xml':'svg'}[m[1]],path='brand/logo.'+ext;const {error}=await db.storage.from('brand-assets').upload(path,bytes,{contentType:m[1],upsert:true,cacheControl:'3600'});if(error)throw error;logoUrl=db.storage.from('brand-assets').getPublicUrl(path).data.publicUrl;
}else if(Object.hasOwn(b,'brandLogo')){if(typeof b.brandLogo!=='string'||b.brandLogo.length>2048)return out({error:'رابط الشعار غير صالح'},400);logoUrl=b.brandLogo.trim()}
const {data:old,error:readErr}=await db.from('brand_settings').select('*').eq('id',1).maybeSingle();if(readErr)throw readErr;
const row={id:1,brand_logo_url:logoUrl??old?.brand_logo_url??null,brand_title:Object.hasOwn(b,'brandTitle')&&typeof b.brandTitle==='string'?b.brandTitle.slice(0,120):(old?.brand_title||''),contact_email:Object.hasOwn(b,'email')&&typeof b.email==='string'?b.email.slice(0,254):(old?.contact_email||''),updated_at:new Date().toISOString()};
const {data,error}=await db.from('brand_settings').upsert(row).select('brand_logo_url,brand_title,contact_email').single();if(error)throw error;return out({success:true,settings:{brandLogo:data.brand_logo_url||'',brandTitle:data.brand_title||'',email:data.contact_email||''}})
}catch(e){console.error('[brand-settings PUT]',e.message);return out({error:'تعذر حفظ الإعدادات أو رفع الصورة.'},500)}}
